skillMatch/urls.py
from django.urls import path

from . import views

app_name = 'skillMatch'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('addfriend/<slug:student_id>/', views.addfriend, name='addfriend'),
    path('removefriend/<slug:student_id>/', views.removefriend, name='removefriend'),
    path('createProfile/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('students/<slug:user_id>/', views.studentProfileView, name='profile'),
    path('students/<slug:user>/edit/', views.StudentUpdateView.as_view(), name='student_edit'),
    path('createPost/<username>/',views.PostCreateView.as_view(),name='post_create'),
    path('posts/<slug:filter>/',views.postListView, name='post_list'),
    path('comment/<user>/<post>/',views.CommentCreateView.as_view(), name='comment'),
    path('createClass/', views.ClassCreateView.as_view(), name='class_create'),
    path('createSkill/', views.SkillCreateView.as_view(), name='skill_create'),
    path('search/', views.studentListView, name='student_list'),
    path('addSkill/', views.skillListView.as_view(), name='skill_list'),
    path('addOneSkill/<slug:user_id>/<slug:skill_id>', views.addSkill, name ='add_skill'),
    path('addClass/', views.classListView.as_view(), name='class_list'),
    path('addOneClass/<slug:user_id>/<slug:class_id>', views.addclass, name ='add_class'),
    path('class/<slug:course_pk>/', views.classDetailView, name='course_details'),

]

thirteenReasonsWhy/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from skillMatch import views
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('skillMatch/', include('skillMatch.urls')),
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE HTML>
<!--
Future Imperfect by HTML5 UP
html5up.net | @ajlkn
Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
{% load static %}
<html>

<head>
	<title>SkillMatch</title>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes" />
	<link rel="stylesheet" href={% static "assets/css/main.css"%} />
</head>

<body class="is-preload">

	<!-- Wrapper -->
	<div id="wrapper">

		<!-- Header -->
		<header id="header">
			<h1><a href={% url 'home' %}>Student Skill Match</a></h1>
			<nav class="links">
				<ul>
					<li><a href={% url 'skillMatch:index' %}>Discover</a></li>
					{% if user.username %}
					<li><a href={% url 'skillMatch:profile' user.username %}>Your Profile</a></li>
					<li><a href={% url 'skillMatch:post_list' True%}>Posts</a></li>
					<li><h4>Logged in as {{ user.get_full_name }}</h4></li>
					{% else %}
					<li><a href={% url 'skillMatch:post_list' False%}>Posts</a></li>
					{% endif %}
					<li></li>
				</ul>
			</nav>
			<nav class="main">
					{% if user.username %}
						<a href="{% url 'logout' %}" class="button medium fit">Logout</a>
					{% else %}
						<a href="{% url 'social:begin' 'google-oauth2' %}" class="button fit">Log In</a>
					{% endif %}
			</nav>
			<nav class="main">
				<ul>
					<li class="search">
						<a class="fa-search" href="#search">Search</a>
						<form id="search" method="get" action="{% url 'skillMatch:student_list' %}">
							<input type="text" name="usr_query" placeholder="Search" value='{{ student_name }}'
								required />
						</form>
					</li>
					<li class="menu">
						<a class="fa-bars" href="#menu">Menu</a>
					</li>
				</ul>
			</nav>
		</header>

		<!-- Menu -->
		<section id="menu">

			<!-- Search -->
			<section>
				<form class="search" method="get" action="{% url 'skillMatch:student_list' %}">
					<input type="text" name="usr_query" placeholder="Search" value='{{ student_name }}' required />
				</form>
			</section>

			<!-- Links -->
			<section>
				<ul class="links">
					<li>
						<a href={% url 'skillMatch:index' %}>
							<h2>Discover</h2>
							<p>Find other students</p>
						</a>
					</li>

					{% if user.username %}
					<li>
						<a href={% url 'skillMatch:profile' user.username %}>
							<h2>Your Profile</h2>
							<p>See and edit your profile</p>
						</a>
					</li>

					<li>
						<a href={% url 'skillMatch:post_list' True %}>
							<h2>Posts</h2>
							<p>See what other students are up to</p>
						</a>
					</li>

					{% else %}
					<li>
						<a href={% url 'skillMatch:post_list' False %}>
							<h2>Posts</h2>
							<p>See what other students are up to</p>
						</a>
					</li>
					{% endif %}
					{#          <li>#}
					{#            <a href="#">#}
					{#              <h3>Etiam sed consequat</h3>#}
					{#              <p>Porta lectus amet ultricies</p>#}
					{#            </a>#}
					{#          </li>#}
				</ul>
			</section>

			<!-- Actions -->
			<div>
				{% if user.username %}
				<div align="center">
					<h4>Logged in as {{ user.get_full_name }}</h4>
					<h5><a class="btn btn-primary" href="{% url 'logout' %}">Logout</a></h5>
				</div>
				{% else %}
				<section>
					<ul class="actions stacked">
						<li><a href="{% url 'social:begin' 'google-oauth2' %}" class="button large fit">Log
								In</a></li>
					</ul>
				</section>
				{% endif %}
			</div>
		</section>

		{% block content %}
		{% endblock %}

		<!-- Sidebar -->
		<section id="sidebar">

			<!-- Intro -->
			<section id="intro">
				<h3 class="logo"><img src={% static "images/logo.jpg" %} /></h3>
				<header>
					<h2>Student Skill Match</h2>
					<p>Find buddies here!</p>
				</header>
			</section>

			<!-- Mini Posts -->
			<section>
				<div class="mini-posts">
					<h2>Creators</h2>
					<!-- Mini Post -->
					<article class="mini-post">
						<header>
							<h3><a href={% url 'skillMatch:profile' 'jf8he' %}>Jacob Fullerton</a></h3>
{#							<a href={% url 'skillMatch:profile' 'jf8he' %} class="author"><img src="https://i.imgur.com/mDVFIvA.jpg" alt="" /></a>#}
						</header>
						<a href={% url 'skillMatch:profile' 'jf8he' %} class="image"><img src="https://i.imgur.com/mDVFIvA.jpg" alt="https://i.imgur.com/Qn95ZJN.png" /></a>
					</article>

					<!-- Mini Post -->
					<article class="mini-post">
						<header>
							<h3><a href={% url 'skillMatch:profile' 'jtr5ee' %}>Jeffery Rhoads</a></h3>
{#							<a href={% url 'skillMatch:profile' 'jtr5ee' %} class="author"><img src="https://i.imgur.com/Qn95ZJN.png" alt="" /></a>#}
						</header>
						<a href={% url 'skillMatch:profile' 'jtr5ee' %} class="image"><img src="https://i.imgur.com/pUjM07h.jpg" alt="https://i.imgur.com/Qn95ZJN.png" /></a>
					</article>

					<!-- Mini Post -->
					<article class="mini-post">
						<header>
							<h3><a href={% url 'skillMatch:profile' 'hlu8jm' %}>Hua Uehara</a></h3>
{#							<a href={% url 'skillMatch:profile' 'hlu8jm' %} class="author"><img src="https://i.imgur.com/Qn95ZJN.png" alt="" /></a>#}
						</header>
						<a href={% url 'skillMatch:profile' 'hlu8jm' %} class="image"><img src="https://i.imgur.com/zSAcCyR.jpg" alt="https://i.imgur.com/Qn95ZJN.png" /></a>
					</article>

					<!-- Mini Post -->
					<article class="mini-post">
						<header>
							<h3><a href={% url 'skillMatch:profile' 'kr6eg' %}>Keerthi Radhakrishnan</a></h3>
{#							<a href={% url 'skillMatch:profile' 'kr6eg' %} class="author"><img src="https://i.imgur.com/Qn95ZJN.png" alt="" /></a>#}
						</header>
						<a href={% url 'skillMatch:profile' 'kr6eg' %} class="image"><img src="https://i.imgur.com/ii13CWi.jpg" alt="https://i.imgur.com/Qn95ZJN.png" /></a>
					</article>

					<!-- Mini Post -->
					<article class="mini-post">
						<header>
							<h3><a href={% url 'skillMatch:profile' 'ab5ep' %}>Austin Baney</a></h3>
{#							<a href={% url 'skillMatch:profile' 'ab5ep' %} class="author"><img src="https://i.imgur.com/Qn95ZJN.png" alt="" /></a>#}
						</header>
						<a href={% url 'skillMatch:profile' 'ab5ep' %} class="image"><img src="https://i.imgur.com/lKdPkaD.jpg" alt="https://i.imgur.com/Qn95ZJN.png" /></a>
					</article>

				</div>
			</section>

			<!-- About -->
			<section class="blurb">
				<h2>About</h2>
				<p>This project was completed from CS 3420 with the purpose to allow students to find others with
					similar interests and collaborate on assignments. </p>

			</section>

			<!-- Posts List -->
			{#	<section>#}
			{#		<ul class="posts">#}
			{#			<li>#}
			{#				<article>#}
			{#					<header>#}
			{#						<h3><a href="single.html">Lorem ipsum fermentum ut nisl vitae</a></h3>#}
			{#						<time class="published" datetime="2015-10-20">October 20, 2015</time>#}
			{#					</header>#}
			{#					<a href="single.html" class="image"><img src={% static "images/pic08.jpg" %}alt="" /></a>#}
			{#				</article>#}
			{#			</li>#}
			{#			<li>#}
			{#				<article>#}
			{#					<header>#}
			{#						<h3><a href="single.html">Convallis maximus nisl mattis nunc id lorem</a></h3>#}
			{#						<time class="published" datetime="2015-10-15">October 15, 2015</time>#}
			{#					</header>#}
			{#					<a href="single.html" class="image"><img src={% static "images/pic09.jpg" %} alt="" /></a>#}
			{#				</article>#}
			{#			</li>#}
			{#			<li>#}
			{#				<article>#}
			{#					<header>#}
			{#						<h3><a href="single.html">Euismod amet placerat vivamus porttitor</a></h3>#}
			{#						<time class="published" datetime="2015-10-10">October 10, 2015</time>#}
			{#					</header>#}
			{#					<a href="single.html" class="image"><img src={% static "images/pic10.jpg" %} alt="" /></a>#}
			{#				</article>#}
			{#			</li>#}
			{#			<li>#}
			{#				<article>#}
			{#					<header>#}
			{#						<h3><a href="single.html">Magna enim accumsan tortor cursus ultricies</a></h3>#}
			{#						<time class="published" datetime="2015-10-08">October 8, 2015</time>#}
			{#					</header>#}
			{#					<a href="single.html" class="image"><img src={% static "images/pic11.jpg" %} alt="" /></a>#}
			{#				</article>#}
			{#			</li>#}
			{#			<li>#}
			{#				<article>#}
			{#					<header>#}
			{#						<h3><a href="single.html">Congue ullam corper lorem ipsum dolor</a></h3>#}
			{#						<time class="published" datetime="2015-10-06">October 7, 2015</time>#}
			{#					</header>#}
			{#					<a href="single.html" class="image"><img src={% static "images/pic12.jpg" %} alt="" /></a>#}
			{#				</article>#}
			{#			</li>#}
			{#		</ul>#}
			{#	</section>#}


			<!-- Footer -->
			<section id="footer">
				<ul class="icons">
					<li><a href="https://twitter.com/MarkSherriff" class="fa-twitter"><span
								class="label">Twitter</span></a></li>
				</ul>
				<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a
						href="http://unsplash.com">Unsplash</a>.</p>
			</section>
</body>

<!-- Scripts -->
<script src={% static "assets/js/jquery.min.js" %}></script>
<script src={% static "assets/js/browser.min.js" %}></script>
<script src={% static "assets/js/breakpoints.min.js" %}></script>
<script src={% static "assets/js/util.js" %}></script>
<script src={% static "assets/js/main.js" %}></script>

</html>

templates/single.html
<!DOCTYPE HTML>
<!--
	Future Imperfect by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>Single - Future Imperfect by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href={% static "assets/css/main.css"%} />
	</head>
	<body class="single is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<h1><a href="index.html">Future Imperfect</a></h1>
						<nav class="links">
							<ul>
								<li><a href="#">Lorem</a></li>
								<li><a href="#">Ipsum</a></li>
								<li><a href="#">Feugiat</a></li>
								<li><a href="#">Tempus</a></li>
								<li><a href="#">Adipiscing</a></li>
							</ul>
						</nav>
						<nav class="main">
							<ul>
								<li class="search">
									<a class="fa-search" href="#search">Search</a>
									<form id="search" method="get" action="#">
										<input type="text" name="query" placeholder="Search" />
									</form>
								</li>
								<li class="menu">
									<a class="fa-bars" href="#menu">Menu</a>
								</li>
							</ul>
						</nav>
					</header>

				<!-- Menu -->
					<section id="menu">

						<!-- Search -->
							<section>
								<form class="search" method="get" action="#">
									<input type="text" name="query" placeholder="Search" />
								</form>
							</section>

						<!-- Links -->
							<section>
								<ul class="links">
									<li>
										<a href="#">
											<h3>Lorem ipsum</h3>
											<p>Feugffffffffffiat tempus veroeros dolor</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Dolor sit amet</h3>
											<p>Sed vitae justo condimentum</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Feugiat veroeros</h3>
											<p>Phasellus sed ultricies mi congue</p>
										</a>
									</li>
									<li>
										<a href="#">
											<h3>Etiam sed consequat</h3>
											<p>Porta lectus amet ultricies</p>
										</a>
									</li>
								</ul>
							</section>

						<!-- Actions -->
							<section>
								<ul class="actions stacked">
									<li><a href="#" class="button large fit">Log In</a></li>
								</ul>
							</section>

					</section>

				<!-- Main -->
					<div id="main">
                        <body>
                        {% block content %}
                            {% if user.is_authenticated %}
                                <p class="display-4">Hello, {{ user.first_name }}</p>
                                <div>Visit <a href="{% url 'skillMatch:student_edit' user.student.pk %}">here </a>to
                                    edit your profile
                                </div>
                                <div>Visit <a href="{% url 'skillMatch:index' %}">here </a>to see students</div>
                            {% else %}
                                <div align="center">
                                    <h1>Welcome to SkillMatch! Start by logging in.</h1>
                                    <font size="16"><a class="btn btn-primary" href="{% url 'login' %}">Log
                                        in</a></font>
                                </div>
                            {% endif %}
                        {% endblock %}
                        </body>
						<!-- Post -->
							<article class="post">
								<header>
									<div class="title">
										<h2><a href="#">Magna sed adipiscing</a></h2>
										<p>Lorem ipsum dolor amet nullam consequat etiam feugiat</p>
									</div>
									<div class="meta">
										<time class="published" datetime="2015-11-01">November 1, 2015</time>
										<a href="#" class="author"><span class="name">Jane Doe</span><img src={% static "images/avatar.jpg"%} alt="" /></a>
									</div>
								</header>
								<span class="image featured"><img src="images/pic01.jpg" alt="" /></span>
								<p>Mauris neque quam, fermentum ut nisl vitae, convallis maximus nisl. Sed mattis nunc id lorem euismod placerat. Vivamus porttitor magna enim, ac accumsan tortor cursus at. Phasellus sed ultricies mi non congue ullam corper. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
								<p>Nunc quis dui scelerisque, scelerisque urna ut, dapibus orci. Sed vitae condimentum lectus, ut imperdiet quam. Maecenas in justo ut nulla aliquam sodales vel at ligula. Sed blandit diam odio, sed fringilla lectus molestie sit amet. Praesent eu tortor viverra lorem mattis pulvinar feugiat in turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce ullamcorper tellus sit amet mattis dignissim. Phasellus ut metus ligula. Curabitur nec leo turpis. Ut gravida purus quis erat pretium, sed pellentesque massa elementum. Fusce vestibulum porta augue, at mattis justo. Integer sed sapien fringilla, dapibus risus id, faucibus ante. Pellentesque mattis nunc sit amet tortor pellentesque, non placerat neque viverra. </p>
								<footer>
									<ul class="stats">
										<li><a href="#">General</a></li>
										<li><a href="#" class="icon fa-heart">28</a></li>
										<li><a href="#" class="icon fa-comment">128</a></li>
									</ul>
								</footer>
							</article>

					</div>

				<!-- Footer -->
					<section id="footer">
						<ul class="icons">
							<li><a href="#" class="fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="fa-instagram"><span class="label">Instagram</span></a></li>
							<li><a href="#" class="fa-rss"><span class="label">RSS</span></a></li>
							<li><a href="#" class="fa-envelope"><span class="label">Email</span></a></li>
						</ul>
						<p class="copyright">&copy; Untitled. Design: <a href="http://html5up.net">HTML5 UP</a>. Images: <a href="http://unsplash.com">Unsplash</a>.</p>
					</section>

			</div>

		<!-- Scripts -->
			<script src= {% static "assets/js/jquery.min.js"%}></script>
			<script src={% static "assets/js/browser.min.js"%}></script>
			<script src={% static "assets/js/breakpoints.min.js"%}></script>
			<script src={% static "assets/js/util.js"%}></script>
			<script src={% static "assets/js/main.js"%}></script>
	</body>
</html>