skillMatch/urls.py
from django.urls import path

from . import views

app_name = 'skillMatch'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('addfriend/<slug:student_id>/', views.addfriend, name='addfriend'),
    path('removefriend/<slug:student_id>/', views.removefriend, name='removefriend'),
    path('createProfile/', views.ProfileCreateView.as_view(), name='profile_create'),
    path('students/<slug:user_id>/', views.studentProfileView, name='profile'),
    path('students/<slug:user>/edit/', views.StudentUpdateView.as_view(), name='student_edit'),
    path('createPost/<username>/',views.PostCreateView.as_view(),name='post_create'),
    path('posts/<slug:filter>/',views.postListView, name='post_list'),
    path('comment/<user>/<post>/',views.CommentCreateView.as_view(), name='comment'),
    path('createClass/', views.ClassCreateView.as_view(), name='class_create'),
    path('createSkill/', views.SkillCreateView.as_view(), name='skill_create'),
    path('search/', views.studentListView, name='student_list'),
    path('addSkill/', views.skillListView.as_view(), name='skill_list'),
    path('addOneSkill/<slug:user_id>/<slug:skill_id>', views.addSkill, name ='add_skill'),
    path('addClass/', views.classListView.as_view(), name='class_list'),
    path('addOneClass/<slug:user_id>/<slug:class_id>', views.addclass, name ='add_class'),
    path('class/<slug:course_pk>/', views.classDetailView, name='course_details'),

]

thirteenReasonsWhy/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from skillMatch import views
from django.conf import settings 
from django.conf.urls.static import static 

urlpatterns = [
    path('skillMatch/', include('skillMatch.urls')),
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name="home"),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skillMatch/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    SEX_CHOICES = [('M', 'Male'), ('F', 'Female'), ('O', 'Other')]
    name = models.CharField(max_length=100)
    # computing_id = models.CharField(max_length=6, unique= True)
    bio = models.TextField()
    sex = models.CharField(choices=SEX_CHOICES, max_length=1, blank=True)
    classes = models.ManyToManyField('Class',blank=True)
    skills = models.ManyToManyField('Skill', blank=True)
    friends = models.ManyToManyField('Student', blank=True)
    picture = models.ImageField(default = "static/default-user.jpg", upload_to='images/')

    def __str__(self):
        return "%s (%s)" % (self.name, self.user.username)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Student.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.student.save()


class Skill(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Class(models.Model):
    prefix = models.CharField(max_length=5)
    course_number = models.CharField(max_length=5)
    professor = models.CharField(max_length=50)
    semester = models.CharField(max_length=3)

    def __str__(self):
        return "%s %s Semester: %s" % (self.prefix, self.course_number, self.semester)


class Post(models.Model):
    author = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=400)
    course = models.ForeignKey(Class, on_delete=models.SET_NULL, null=True, blank=True)  # up to 1 optional relevant course
    skills = models.ManyToManyField('Skill', blank=True)    # optional relevant skills
    date = models.DateTimeField(auto_now_add=True) # captures time of object creation
    # likes = models.IntegerField()   # upvote and downvote feature?

class Comment(models.Model):
    author = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    content = models.CharField(max_length=400)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)    # each comment relates to ONE post
    date = models.DateTimeField(auto_now_add=True) # captures time of object creation

skillMatch/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from .models import Student
from django.contrib.auth.models import User

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ('name', 'sex', 'bio', 'picture')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'Save'))

skillMatch/views.py
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone

from .forms import StudentForm
from .models import Student, Skill, Class, Post, Comment

class Meta:
    ordering = ['-id']

class IndexView(generic.ListView):
    template_name = 'skillMatch/index.html'
    model = Student
    context_object_name = 'students'
    paginate_by = 5


class ProfileCreateView(generic.CreateView):
    model = Student
    fields = ('name', 'sex', 'bio', 'classes', 'skills', 'picture')
    success_url = reverse_lazy('skillMatch:index')


def studentProfileView(request, user_id):
    person = get_object_or_404(User, username=user_id)
    person_classes = person.student.classes.all().order_by('id')
    person_skills = person.student.skills.all().order_by('id')
    person_friends = person.student.friends.all().order_by('id')
    picture = person.student.picture
    context = {
        'person': person,
        'person_classes': person_classes,
        'person_skills': person_skills,
        'person_friends': person_friends,
        'picture': picture
    }
    return render(request, 'skillMatch/student.html', context)

def classDetailView(request, course_pk) :
    course = get_object_or_404(Class, pk=course_pk)
    students = course.student_set.all().order_by('id')
    context = {
        'course' : course,
        'students' : students
    }
    return render(request, 'skillMatch/course_details.html', context)


class StudentUpdateView(generic.UpdateView):
    model = Student
    form_class = StudentForm
    template_name = 'skillMatch/student_update_form.html'
    success_url = reverse_lazy('skillMatch:index')
    slug_field = 'user'
    slug_url_kwarg = 'user'

    def get_object(self, queryset=None):
        return Student.objects.get(user__username=self.request.user)


class ClassCreateView(generic.CreateView):
    model = Class
    fields = ('prefix', 'course_number', 'professor', 'semester')
    success_url = reverse_lazy('skillMatch:class_list')


class SkillCreateView(generic.CreateView):
    model = Skill
    fields = ('name',)
    success_url = reverse_lazy('skillMatch:skill_list')


class PostCreateView(generic.CreateView):
    model = Post
    fields = ('title', 'content', 'course', 'skills')
    success_url = reverse_lazy('skillMatch:post_list', kwargs={'filter':'True'})
    def form_valid(self, form):
        uname = self.kwargs['username']
        mystudent = Student.objects.get(user__username=uname)
        form.instance.author = mystudent
        return super(PostCreateView, self).form_valid(form)
    # def get_success_url(self):
    #     uname = self.kwargs['username']
    #     self.object.author = Student.objects.get(user__username=uname)
    #     return reverse_lazy('skillMatch:index')


class CommentCreateView(generic.CreateView):
    model = Comment
    fields = ('content',)
    success_url = reverse_lazy('skillMatch:post_list', kwargs={'filter':'True'})

    def form_valid(self, form):
        uname = self.kwargs['user']
        mystudent = Student.objects.get(user__username=uname)
        form.instance.author = mystudent

        postID = self.kwargs['post']
        mypost = Post.objects.get(pk=postID)
        form.instance.post = mypost

        return super(CommentCreateView, self).form_valid(form)


def studentListView(request):
    students = set()
    computing_id = request.GET.get('usr_query', '')
    student_name = request.GET.get('usr_query', '')
    class_name = request.GET.get('usr_query', '')

    id_results = Student.objects.filter(user__username__icontains=computing_id)
    first_name_results = Student.objects.filter(user__first_name__icontains=student_name)
    last_name_results = Student.objects.filter(user__last_name__icontains=student_name)

    students.update(id_results)
    students.update(first_name_results)
    students.update(last_name_results)

    classes = set()
    classes.update(Class.objects.filter(prefix__icontains=class_name))
    classes.update(Class.objects.filter(course_number__icontains=class_name))
    classes.update(Class.objects.filter(semester__icontains=class_name))
    classes.update(Class.objects.filter(professor__icontains=class_name))

    skills = set()
    skills.update(Skill.objects.filter(name__icontains=class_name))

    context = {
        'matching_students': students,
        'matching_classes' : classes,
        'matching_skills' : skills
    }

    return render(request, 'skillMatch/student_list.html/', context)



def addfriend(request, student_id):
    friend_being_added = Student.objects.get(user__username=student_id)
    person_adding_friend = Student.objects.get(user__username=request.user)
    person_adding_friend.friends.add(friend_being_added)
    person_adding_friend.save()
    return studentProfileView(request, request.user.username)


def removefriend(request, student_id):
    friend_being_removed = Student.objects.get(user__username=student_id)
    person_removing_friend = Student.objects.get(user__username=request.user)
    person_removing_friend.friends.remove(friend_being_removed)
    person_removing_friend.save()
    return studentProfileView(request, request.user.username)


class skillListView(generic.ListView):
    template_name = 'skillMatch/skill_list.html'
    model = Skill
    context_object_name = 'skills'
    paginate_by = 15


def addSkill(request, user_id, skill_id):
    person = get_object_or_404(User, username=user_id)
    student = person.student
    person_skills = person.student.skills.all().order_by('id')
    skill = Skill.objects.filter(id=skill_id).values_list('id', flat=True)
    student.skills.add(skill[0])
    # student.update()
    return render(request, 'skillMatch/success.html')


class classListView(generic.ListView):
    template_name = 'skillMatch/class_list.html'
    model = Class
    context_object_name = 'classes'
    paginate_by = 15


def addclass(request, user_id, class_id):
    person = get_object_or_404(User, username=user_id)
    student = person.student
    person_class = person.student.classes.all().order_by('id')
    classToAdd = Class.objects.filter(id=class_id).values_list('id', flat=True)
    student.classes.add(classToAdd[0])
    # student.update()
    return render(request, 'skillMatch/success.html')



def postListView(request, filter): # displays every post from newest to oldest, optionally filters for friend posts only
    # add message if filter on but no friends added?
    if filter == "True":  # may only pass in True if user is logged in
        authors = set()
        me = Student.objects.get(user__username=request.user)
        friends = me.friends.all().order_by('id')
        authors.update(friends)
        authors.update({me})
        posts_ordered = Post.objects.filter(author__in=authors).order_by('-date')
    else:
        posts_ordered = Post.objects.all().order_by('-date')


    if posts_ordered:
        post_results = [{'id': post.id, 'author_user': post.author.user.username, 'author_name': post.author.name, 'author_picture': post.author.picture.url,
                         'title': post.title, 'content': post.content, 'course': str(post.course),
                         'skills': [skill.name for skill in post.skills.all()],
                         'comments': [{'author_user': comment.author.user.username, 'author_name': comment.author.name, 'content': comment.content} for comment in Comment.objects.filter(post=post).order_by('date')],
                         'date': post.date}
                        for post in posts_ordered]
        context = {
            'post_results': post_results,
            'filter': filter,
        }
    else:
        context = {}

    return render(request, 'skillMatch/post_list.html/', context)

templates/skillMatch/class_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div id="main">
    {% if classes %}
        <ul>
        <ul class="actions">
        <li><a href = "{% url 'skillMatch:class_create' %}" class="button large">Create a New Class</a></li>
        </ul>
            {% for class in classes %}
				<article class="post">
					<header>
						<div class="title">
							<h2>{{ class.prefix}}  {{ class.course_number }}  {{ class.professor }}  {{ class.semester }} </h2>
						</div>
					</header>


					<footer>
						<ul class="actions">
							<li><a href = '{% url "skillMatch:add_class" user.username class.id %}' class="button large">Add this Class</a></li>
						</ul>
					</footer>
				</article>
            {% endfor %}
        </ul>
    {% else %}
        No matching classes.
    {% endif %}
 </div>
{% endblock %}

templates/skillMatch/index.html
{% extends 'base.html' %}
{% load static %}
{% load extras %}
{% block content %}

<!-- Main -->
<div id="main">
	<!-- Post -->
	{% if students %}
	{% for person in students %}
	{% if person.user.email %}
	<article class="post">
		<header>
			<div class="title">
				<h2><a href={% url 'skillMatch:profile' person.user %}>{{ person.user.get_full_name }}</a></h2>
			</div>
			<div class="meta">
				<a href={% url 'skillMatch:profile' person.user %} class="author">
				<!-- <span class="name">
                                {{ person.blurb }}
                            </span> -->

				<img src="{{ person.picture.url }}" onerror="this.onerror=null; this.src='https://skillmatch13-media.s3.amazonaws.com/media/images/default-user.jpg';" class="img-responsive" />
				</a>
			</div>
		</header>

		<p>{{ person.bio }}</p>

		{% if person not in user.student.friends.all and person != user.student %}
		{% if user.student|common:person > 1 %}
		{% if user.student|mutual:person > 1 %}
		<p>You have {{ user.student|common:person }} classes and {{ user.student|mutual:person }} friends in common! </p>
		{% elif user.student|mutual:person == 1 %}
		<p>You have {{ user.student|common:person }} classes and 1 friend in common! </p>
		{% else %}
		<p>You have {{ user.student|common:person }} classes in common! </p>
		{% endif %}
		{% elif user.student|common:person == 1 %}
		{% if user.student|mutual:person > 1 %}
		<p>You have 1 class and {{ user.student|mutual:person }} friends in common! </p>
		{% elif user.student|mutual:person == 1 %}
		<p>You have 1 class and 1 friend in common! </p>
		{% else %}
		<p>You have 1 class in common! </p>
		{% endif %}
		{% else %}
		{% if user.student|mutual:person > 1 %}
		<p>You have {{ user.student|mutual:person }} friends in common! </p>
		{% elif user.student|mutual:person == 1 %}
		<p>You have 1 friend in common! </p>
		{% endif %}
		{% endif %}
		{% endif %}

		<footer>
			{% if user.username %}
			{% if person == user.student %}
			<h4>Your Profile</h4>
			{% elif person in user.student.friends.all %}
			<form action="{% url 'skillMatch:removefriend' person.user %}" method="post">
				{% csrf_token %}
				<input type="submit" class="button large" value="Remove Friend">
			</form>
			{% else %}
			<form action="{% url 'skillMatch:addfriend' person.user %}" method="post">
				{% csrf_token %}
				<input type="submit" class="button large" value="Add Friend">
			</form>
			{% endif %}
			{% endif %}
		</footer>
	</article>
	{% endif %}
	{% endfor %}
	{% endif %}


	<!-- Pagination -->
	<ul class="actions pagination">
		{% if page_obj.has_previous %}
		<li><a href="?page={{ page_obj.previous_page_number }}" class="button large previous">Previous Page</a></li>
		{% endif %}

		{% if page_obj.has_next %}
		<li><a href="?page={{ page_obj.next_page_number }}" class="button large next">Next Page</a></li>
		{% endif %}
	</ul>
</div>

{% endblock %}

templates/skillMatch/post_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
 <div id="main">
	<!-- <article class="post"> -->
		<ul class="actions">
			{% if user.username %}
			<li><a href={% url 'skillMatch:post_create' user.username %} class="button large">Create Post</a></li>
				{% if filter == "True" %}
				<li><a href={% url 'skillMatch:post_list' False %} class="button large">Show All Posts</a></li>
				{% else %}
				<li><a href={% url 'skillMatch:post_list' True %} class="button large">Show Posts From Friends</a></li>
				{% endif %}
			{% endif %}
		</ul>
	<!-- </article> -->
    {% if post_results %}
        <ul>
            {% for post in post_results %}
				<article class="post">
					<header>
						<div class="title">
							<h2>{{ post.title }}</a></h2>
							<p><a href={% url 'skillMatch:profile' post.author_user %}>{{ post.author_name }}</a></p>
						</div>
						<div class="meta">
							<a href="#" class="author">
								<!-- <span class="name">
									{{ person.name }}
								</span> -->
								<img src="{{ post.author_picture }}" class="img-responsive" />
							</a>
						</div>
					</header>

					<div>
					<p>{{ post.content }}</p>
					</div>

					<footer>
						<div>
						{% if post.course != 'None' %}
							<ul>
								<h3>Related Course: </h3>
								<p>{{ post.course }}</p>
							</ul>
						{% endif %}
						</div>
						<div>
						{% if post.skills %}
							<ul class="list-group">
								<h3>Related Skills:</h3>
								{% for skill in post.skills %}
									<p>{{ skill }}</p>
								{% endfor %}
							</ul>
						{% endif %}
						</div>

						<!-- <ul class="stats">
							<li><a href="#">General</a></li>
							<li><a href="#" class="icon fa-heart">28</a></li>
							<li><a href="#" class="icon fa-comment">128</a></li>
						</ul> -->
					</footer>

					{% if post.comments %}
						{% for comment in post.comments %}
							<article class="mini-post">
								<header>
									<b><a href={% url 'skillMatch:profile' comment.author_user %}> {{ comment.author_name }} </a></b>
									{{ comment.content }}
								</header>
							</article>
						{% endfor %}
					{% endif %}
					{% if user.username %}
						<a href={% url 'skillMatch:comment' user.username post.id %} class="button large">Add Comment</a>
					{% endif %}
				</article>
            {% endfor %}
        </ul>
    {% else %}
        No matching posts.
    {% endif %}
 </div>
{% endblock %}

templates/skillMatch/skill_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div id="main">
    <ul class="actions">
        <li><a href = "{% url 'skillMatch:skill_create' %}" class="button large">Create a New Skill</a></li>
    </ul>
    {% if skills %}
        <ul>
            {% for skill in skills %}
				<article class="post">
					<header>
						<div class="title">
							<h2>{{ skill.name }}</h2>
						</div>
					</header>

					<footer>
						<ul class="actions">
							<li><a href = '{% url "skillMatch:add_skill" user.username skill.id %}' class="button large">Add this skill</a></li>
						</ul>
					</footer>
				</article>
            {% endfor %}
        </ul>
    {% else %}
        No matching skills.
    {% endif %}
 </div>
{% endblock %}

templates/skillMatch/student.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Main -->
<div id="main">
	<!-- Post -->
	<article class="post">
		<header>
			<div class="title">
				<h2>{{ person.get_full_name }}</h2>
				<p>Student at the University of Virginia</p>
			</div>
			<div class="meta">
				<!-- Maybe add a graduation date or time spent at UVa? -->
				<!-- <time class="published" datetime="2015-11-01">November 1, 2015</time> -->

				<h3 class="author">
					<img src="{{ person.student.picture.url }}" onerror="this.onerror=null; this.src='https://skillmatch13-media.s3.amazonaws.com/media/images/default-user.jpg';" class="img-responsive" />
				</h3>
			</div>
		</header>
		
		<!-- <span class="image featured">
			<img src="images/pic01.jpg" alt="" />
		</span> -->
		
		<div class="bio">
			<h2>
				Bio:
			</h2>
			{% if person.student.bio %}
				<p>{{ person.student.bio }}</p>
			{% else %}
				{% if user == person %}
					<p>You haven't input a bio yet!</p>
				{% else %}
					{{ person.get_full_name }} hasn't input a bio yet.
				{% endif %}
			{% endif %}
		</div>
		
		<br>

		<div class="classes">
			<h2>
				Classes:
			</h2>
			{% if person_classes %}
				<ul>
					{% for class in person_classes %}
					<a href={% url 'skillMatch:course_details' class.pk %} >{{ class }}</a> <br>
					{% endfor %}
				</ul>
			{% else %}
				{% if user == person %}
					<p>You haven't input any classes yet!</p>
				{% else %}
					{{ person.get_full_name }} hasn't input any classes yet.
				{% endif %}
			{% endif %}
		</div>

		<br>

		<div class="skills">
			<h2>
				Skills:
			</h2>
			{% if person_skills %}
				<ul>
					{% for skill in person_skills %}
						{{ skill }} <br>
					{% endfor %}
				</ul>
			{% else %}
				{% if user == person %}
					<p>You haven't input any skills yet!</p>
				{% else %}
					{{ person.get_full_name }} hasn't input any skills yet.
				{% endif %}
			{% endif %}
		</div>

		<div class="friends">
			<h2>
				Friends:
			</h2>
			{% if person_friends %}
				<ul>
					{% for friend in person_friends %}
						<a href={% url 'skillMatch:profile' friend.user %}>{{ friend.user.get_full_name }}</a> <br>
					{% endfor %}
				</ul>
			{% else %}
				{% if user == person %}
					<p>You haven't added any friends yet!</p>
				{% else %}
					{{ person.get_full_name }} hasn't added any friends yet.
				{% endif %}
			{% endif %}
		</div>
		{% if user.username %}
			{% if user == person %}
			{% elif person.student in user.student.friends.all %}
				<form action="{% url 'skillMatch:removefriend' person.username %}" method="post">
					{% csrf_token %}
					<input type="submit" class="button large" value="Remove Friend">
				</form>
			{% else %}
				<form action="{% url 'skillMatch:addfriend' person.username %}" method="post">
					{% csrf_token %}
					<input type="submit" class="button large" value="Add Friend">
				</form>
			{% endif %}
		{% endif %}
		<br>
		<footer>
			{% if user == person %}
				<a href="{% url 'skillMatch:student_edit' person.username %}" class="button large previous">Edit Profile</a>
                <a href="{% url 'skillMatch:skill_list'  %}" class="button large previous"> Add Skill</a>
                <a href="{% url 'skillMatch:class_list'  %}" class="button large previous">Add Class</a>
			{% endif %}
		</footer>
	</article>
</div>
{% endblock %}

templates/skillMatch/student_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load extras %}

{% block content %}
    <div id="main">
    {% if matching_students %}
        <ul>
            {% for person in matching_students %}
			{% if person.user.email %}
				<article class="post">
					<header>
						<div class="title">
							<h2><a href={% url 'skillMatch:profile' person.user %}>{{ person.user.get_full_name }}</a></h2>
						</div>
						<div class="meta">
							<a href="#" class="author">
								<!-- <span class="name">
									{{ person.name }}
								</span> -->
								<img src="{{ person.picture.url }}" onerror="this.onerror=null; this.src='https://skillmatch13-media.s3.amazonaws.com/media/images/default-user.jpg';" class="img-responsive" />
							</a>
						</div>
					</header>

					<p>Bio: {{ person.bio }}</p>

					{% if person not in user.student.friends.all and person != user.student %}
						{% if user.student|common:person > 1 %}
							{% if user.student|mutual:person > 1 %}
								<p>You have {{ user.student|common:person }} classes and {{ user.student|mutual:person }} friends in common! </p>
							{% elif user.student|mutual:person == 1 %}
								<p>You have {{ user.student|common:person }} classes and 1 friend in common! </p>
							{% else %}
								<p>You have {{ user.student|common:person }} classes in common! </p>
							{% endif %}
						{% elif user.student|common:person == 1 %}
							{% if user.student|mutual:person > 1 %}
								<p>You have 1 class and {{ user.student|mutual:person }} friends in common! </p>
							{% elif user.student|mutual:person == 1 %}
								<p>You have 1 class and 1 friend in common! </p>
							{% else %}
								<p>You have 1 class in common! </p>
							{% endif %}
						{% else %}
							{% if user.student|mutual:person > 1 %}
								<p>You have {{ user.student|mutual:person }} friends in common! </p>
							{% elif user.student|mutual:person == 1 %}
								<p>You have 1 friend in common! </p>
							{% endif %}
						{% endif %}
					{% endif %}

					<footer>
						{% if user.username %}
							{% if person == user.student %}
								<h4>Your Profile</h4>
							{% elif person in user.student.friends.all %}
								<form action="{% url 'skillMatch:removefriend' person.user %}" method="post">
									{% csrf_token %}
									<input type="submit" class="button large" value="Remove Friend">
								</form>
							{% else %}
							<form action="{% url 'skillMatch:addfriend' person.user %}" method="post">
									{% csrf_token %}
									<input type="submit" class="button large" value="Add Friend">
							</form>
							{% endif %}
						{% endif %}
			
					<!-- <ul class="actions">

					</ul> -->
{#						<ul class="stats">#}
{#							<li><a href="#">General</a></li>#}
{#							<li><a href="#" class="icon fa-heart">28</a></li>#}
{#							<li><a href="#" class="icon fa-comment">128</a></li>#}
{#						</ul>#}
					</footer>
				</article>
			</ul>
			{% endif %}
            {% endfor %}


	{% elif matching_classes %}
		<ul>
			{% for class in matching_classes %}
				<article class="post">
					<header>
						<div class="title">
							<h2><a href='#'>{{ class }}</a></h2>
						</div>
					</header>

					<footer>
							{% if user.username %}
							{% if person == user.student %}
								<h4>Your Profile</h4>
							{% elif class in user.student.classes.all %}
								<h4>Already added class</h4>
							{% else %}
							<form action="{% url 'skillMatch:add_class' user.username class.id %}" method="post">
									{% csrf_token %}
									<input type="submit" class="button large" value="Add Class">
								</form>
								{% endif %}
						{% endif %}
		
{#						<ul class="stats">#}
{#							<li><a href="#">General</a></li>#}
{#							<li><a href="#" class="icon fa-heart">28</a></li>#}
{#							<li><a href="#" class="icon fa-comment">128</a></li>#}
{#						</ul>#}
					</footer>
				</article>
			{% endfor %}
		</ul>

	{% elif matching_skills %}
		<ul>
			{% for skill in matching_skills %}
				<article class="post">
					<header>
						<div class="title">
							<h2><a href="#">{{ skill }}</a></h2>
						</div>
					</header>

					<footer>
							{% if user.username %}
							{% if person == user.student %}
								<h4>Your Profile</h4>
							{% elif skill in user.student.skills.all %}
								<h4>Already added skill</h4>
							{% else %}
							<form action="{% url 'skillMatch:add_skill' user.username skill.id %}" method="post">
									{% csrf_token %}
									<input type="submit" class="button large" value="Add Skill">
								</form>
								{% endif %}
						{% endif %}
			
{#						<ul class="stats">#}
{#							<li><a href="#">General</a></li>#}
{#							<li><a href="#" class="icon fa-heart">28</a></li>#}
{#							<li><a href="#" class="icon fa-comment">128</a></li>#}
{#						</ul>#}
					</footer>
				</article>
			{% endfor %}
    {% else %}
        No matching results.
        <ul class="actions">
        <li><a href = "{% url 'skillMatch:skill_create' %}" class="button large">Create a New Skill</a></li>
        </ul>
        <ul class="actions">
        <li><a href = "{% url 'skillMatch:class_create' %}" class="button large">Create a New Class</a></li>
        </ul>
    {% endif %}
 </div>
{% endblock %}